add_rules("mode.debug", "mode.release")

package("qt-ads")
    add_deps("cmake")
    set_sourcedir(path.join(os.scriptdir(), "/3rd/qt-ads"))
    on_install(function(package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
package_end()

package("libirrlicht")
    set_sourcedir(path.join(os.scriptdir(), "/3rd/libirrlicht"))
    on_install(function(package)
        import("package.tools.xmake").install(package)
    end)
package_end()

add_requires("qt-ads", {configs = {vs_runtime = "MD", shared = true}})
add_requires("libirrlicht")

target("demo")
    add_rules("qt.widgetapp")
    add_defines("IRRLICHT_EXPORTS=0")
    add_includedirs("3rd/qt-ads/src", "3rd/libirrlicht/include/irrlicht")
    add_headerfiles("src/*.h")
    add_files("src/*.cpp")
    add_files("src/MainWindow.ui")
    add_files("src/MainWindow.h")
    add_files("src/IrrlichtWidget.h")
    add_packages("qt-ads")
    add_packages("libirrlicht")
